# Generated by Django 5.2.1 on 2025-06-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="John Doe", max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(default="pasword123", max_length=100)),
                ("phone", models.CharField(default="1234567890", max_length=15)),
                (
                    "address",
                    models.CharField(
                        default="123 Main St, City, Country", max_length=255
                    ),
                ),
                ("city", models.CharField(default="City", max_length=100)),
                ("state", models.CharField(default="State", max_length=100)),
                ("country", models.CharField(default="Country", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("sentiment", models.CharField(max_length=20)),
                ("keywords", models.TextField()),
                ("product_url", models.URLField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="analyzer.user"
                    ),
                ),
            ],
        ),
    ]
