# Generated by Django 5.2.1 on 2025-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
