# Generated by Django 5.2.1 on 2025-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_review_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
