# Generated by Django 5.2.3 on 2025-06-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0003_alter_review_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="platform",
            field=models.CharField(default="Unknown Platform", max_length=50),
        ),
        migrations.AddField(
            model_name="review",
            name="product_name",
            field=models.CharField(default="Unknown Product", max_length=255),
        ),
        migrations.AlterField(
            model_name="review",
            name="product_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="password123", max_length=100),
        ),
    ]
